url <- "https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip"
download.file(url, "data.zip")
unzip("data.zip")
data <- read.table("household_power_consumption.txt", sep=";", stringsAsFactor = FALSE)
names(data) <- data[1,]
data <- data[data$Date == "1/2/2007" | data$Date == "2/2/2007",]
data$Global_reactive_power <- as.numeric(data$Global_reactive_power)
data$Voltage <- as.numeric(data$Voltage)
data$Sub_metering_1 <- as.numeric(data$Sub_metering_1)
data$Sub_metering_2 <- as.numeric(data$Sub_metering_2)
data$Sub_metering_3 <- as.numeric(data$Sub_metering_3)
datetime <- strptime(paste(data$Date, data$Time), "%d/%m/%Y %H:%M:%S")
png("plot4.png")
par(mfrow = c(2,2))
plot(datetime, data$Global_active_power, xlab = "", ylab = "Global Active Power", type = "l")
with(data, plot(datetime, Voltage, type = "l"))
plot(datetime, data$Sub_metering_1, xlab = "", ylab = "Energy sub metering", type = "n")
points(datetime, data$Sub_metering_1, type = "l")
points(datetime, data$Sub_metering_2, col = "red", type = "l")
points(datetime, data$Sub_metering_3, col = "blue", type = "l")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = c(1, 1, 1), col = c("black", "red", "blue"))
with(data, plot(datetime, Global_reactive_power, type = "l"))
dev.off()